In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0,0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0,2,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3,0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0,0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0,0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [9]:
dep=dataset[['classification_yes']]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.3,random_state=0)

In [11]:
'''from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)'''

'from sklearn.preprocessing import StandardScaler\nsc=StandardScaler()\nx_train=sc.fit_transform(x_train)\nx_test=sc.transform(x_test)'

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
param_grid={
    'n_neighbors':[3, 5, 7, 9, 11],
    'weights':['uniform','distance'],
    'algorithm':['auto','ball_tree','kd_tree','brute'],
    'p':[1, 2]    
}
grid=GridSearchCV(KNeighborsClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 80 candidates, totalling 400 fits

C:\Users\AH22634\AppData\Local\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 5, 7, 9, 11], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='f1_weighted', verbose=3)

In [13]:
print("Best Parameter {}".format(grid.best_params_))

Best Parameter {'algorithm': 'auto', 'n_neighbors': 9, 'p': 1, 'weights': 'distance'}

In [14]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.029781,0.014226,0.021211,0.009024,auto,3,1,uniform,"{'algorithm': 'auto', 'n_neighbors': 3, 'p': 1...",0.658966,0.770307,0.681034,0.753906,0.783471,0.729537,0.049995,37
1,0.023388,0.004652,0.017465,0.006159,auto,3,1,distance,"{'algorithm': 'auto', 'n_neighbors': 3, 'p': 1...",0.697759,0.753205,0.714286,0.789032,0.783471,0.747551,0.036411,17
2,0.016080,0.011634,0.035211,0.024501,auto,3,2,uniform,"{'algorithm': 'auto', 'n_neighbors': 3, 'p': 2...",0.566667,0.683548,0.699632,0.736088,0.764621,0.690111,0.067879,77
3,0.025089,0.012273,0.017674,0.004082,auto,3,2,distance,"{'algorithm': 'auto', 'n_neighbors': 3, 'p': 2...",0.645722,0.700820,0.733254,0.771542,0.783471,0.726962,0.050007,45
4,0.015948,0.008801,0.021864,0.005286,auto,5,1,uniform,"{'algorithm': 'auto', 'n_neighbors': 5, 'p': 1...",0.700900,0.701247,0.716475,0.753906,0.730070,0.720520,0.019893,53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.049375,0.020011,0.043374,0.009370,brute,9,2,distance,"{'algorithm': 'brute', 'n_neighbors': 9, 'p': ...",0.718050,0.736395,0.734970,0.736395,0.730070,0.731176,0.006962,33
76,0.060335,0.028030,0.047306,0.021038,brute,11,1,uniform,"{'algorithm': 'brute', 'n_neighbors': 11, 'p':...",0.789032,0.824219,0.682692,0.753871,0.692197,0.748402,0.054600,13
77,0.084522,0.041519,0.053036,0.038661,brute,11,1,distance,"{'algorithm': 'brute', 'n_neighbors': 11, 'p':...",0.771277,0.771542,0.733254,0.771542,0.766061,0.762735,0.014888,5
78,0.059990,0.018901,0.057919,0.023035,brute,11,2,uniform,"{'algorithm': 'brute', 'n_neighbors': 11, 'p':...",0.753906,0.735075,0.648387,0.700900,0.728409,0.713335,0.036657,61
79,0.081585,0.015864,0.046588,0.019664,brute,11,2,distance,"{'algorithm': 'brute', 'n_neighbors': 11, 'p':...",0.718050,0.718750,0.716475,0.753871,0.728409,0.727111,0.014021,41

In [15]:
y_pred=grid.predict(x_test)

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[42  3]
 [23 52]]

In [17]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.65      0.93      0.76        45
           1       0.95      0.69      0.80        75

    accuracy                           0.78       120
   macro avg       0.80      0.81      0.78       120
weighted avg       0.83      0.78      0.79       120

In [18]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])
print(roc)

0.8645925925925926

In [19]:
res1=grid.predict([[8,50,4,0,148.112676,46,1,135,3.8,12.518156,38.868902,8408.191126,4.705597,0,0,0,0,1,1,0,0,0,0,0,1,1,0]])
print(res1)

[1]

C:\Users\AH22634\AppData\Local\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [20]:
res2=grid.predict([[28,70,0,0,131,29,0.6,145,4.9,12.518156,45,8600,6.5,0,0,0,0,1,1,0,0,0,0,0,1,0,0]])
print(res2)

[0]

C:\Users\AH22634\AppData\Local\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [21]:
#to save the model
import pickle
filename='KNN classification assignment.sav'
pickle.dump(grid,open(filename,'wb'))

In [22]:
#to load the model
lm=pickle.load(open(filename,'rb'))
result=lm.predict([[28,70,0,0,131,29,0.6,145,4.9,12.518156,45,8600,6.5,0,0,0,0,1,1,0,0,0,0,0,1,0,0]])
print(result)

[0]

C:\Users\AH22634\AppData\Local\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(